### ISSUE TITLE
v0.2.0: No Intel Mac (x64) build

### ISSUE THREAD

**Issue by storytracer** [describo/desktop#2]
The v0.2.0 release does not contain a build for Intel Macs (x64), just one for ARM Macs (arm64). I would love to try the new version, but my laptop is an Intel Mac.

**Comment by marcolarosa** [comment]
Hi, no there wasn't. I've just released a new version with a build for Intel Macs. See the releases page @ https://github.com/describo/desktop/releases/tag/v0.3.0. Look for `x64.dmg`

**Comment by marcolarosa** [comment]
hi @storytracer Have you had a chance to test the Mac Intel version of the app? Is it working?
